### ISSUE TITLE
Add a "dark mode" theme

### ISSUE THREAD

**Issue by ericeasthope** [arxiv-vanity/arxiv-vanity#517]
For users who would benefit from a low-light reading experience, perhaps a dark theme could be added? WebKit [adds dark mode support](https://webkit.org/blog/8840/dark-mode-support-in-webkit/) through the `colour-scheme` style property, but I anticipate things becoming a little messy when choosing how to render/color PDF content (especially embedded images).

I'm happy to contribute but could use some guidance on possible development directions. Thanks!

**Comment by stereosteve** [comment]
Just learned about arxiv-vanity, which is great.  Came to ask for the same.

It seem it should not be too hard, adding this to the bottom of `main.css` looks to get pretty close:

```css
@media (prefers-color-scheme: dark) {
  html,
  body {
    height: 100%;
    background: #222;
    color: white;
  }

  .wtf-is-this-bar {
    border-bottom: 1px solid rgba(0, 0, 0, 0.1);
    background: #111;
  }

  .ltx_page_main .ltx_document {
    background: transparent !important;
  }
}
```
